version: "3.8"
services:
  telegram_bot_server:
    image: aiogram/telegram-bot-api:latest
    ports:
      - "8081:8081"
    volumes:
      - shared_volume:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=23823287
      - TELEGRAM_API_HASH=fe561473a06737cb358db923e05e7868
      - TELEGRAM_LOCAL=True
    restart: always
    networks:
      - app_network


volumes:
  shared_volume:

networks:
  app_network:
    external: true