name: Insighter deployment
on:
  push:
    branches:
      - main
jobs:
    deploy_docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              deploy/prod/docker-compose.yml
            sparse-checkout-cone-mode: false
        - name: Load SSH aws key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{secrets.PRODUCTION_SERVER_PRIVAT_KEY}}
        - name: Add SSH key to known_hosts
          run: ssh-keyscan -H "${{vars.PRODUCTION_SERVER_HOST}}" >> ~/.ssh/known_hosts

        - name: Deploy
          run: |
            docker context create prod_context --docker "host=ssh://${{vars.PRODUCTION_SERVER_SSH_ROUTE}}" || true
            docker --context prod_context compose -f deploy/prod/docker-compose.yml down --rmi all
            docker --context prod_context compose -f deploy/prod/docker-compose.yml up -d --wait --wait-timeout 60

    
    
