name: Insighter deployment
on:
  push:
    branches:
      - stage
jobs:
    deploy_docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              deploy/stage/docker-compose.yml
            sparse-checkout-cone-mode: false
        - name: Load SSH aws key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{secrets.STAGE_PRIVATE_KEY}}
        - name: Add SSH key to known_hosts
          run: ssh-keyscan -H "${{vars.STAGE_HOST_ADRESS}}" >> ~/.ssh/known_hosts

        - name: Deploy
          run: |
            docker context create stage_context --docker "host=ssh://${{vars.STAGE_SSH_ADRESS}}" || true
            docker --context stage_context compose -f deploy/stage/docker-compose.yml down --rmi all
            
            docker --context stage_context compose -f deploy/stage/docker-compose.yml up -d --wait --wait-timeout 60